"""Validate that committed generated JSON matches a fresh regeneration.

WHY: The authored TOML source is canonical; the JSON under ``data/export/`` is
generated. If someone edits the source but forgets to re-export (or edits the
generated JSON by hand), the two drift apart silently. ``validate-generated``
regenerates in memory and compares against what is committed, so drift is a
hard failure in CI.

It checks three things:
- Every export the source would produce exists on disk.
- No stale export JSON exists that the source would no longer produce.
- Each committed export file is byte-identical to a fresh regeneration.
"""

from dataclasses import dataclass, field
from pathlib import Path
import tomllib

from accountable_record.ops.exporters.canonical_json import to_canonical_json
from accountable_record.ops.exporters.data_export import build_plans


@dataclass
class GeneratedValidation:
    """Result of validating generated output against source.

    Attributes:
        failures: Human-readable drift messages. Empty means in sync.
        compared: Number of files compared.
    """

    failures: list[str] = field(default_factory=list)
    compared: int = 0

    @property
    def ok(self) -> bool:
        """True when generated output matches the source."""
        return not self.failures


def _expected_outputs(root: Path) -> tuple[dict[str, str], list[str]]:
    """Return {repo-relative json path -> expected canonical text} and errors."""
    resolved_root = root.resolve()
    plans, errors = build_plans(resolved_root)
    expected: dict[str, str] = {}

    for plan in plans:
        if plan.is_dir:
            for toml_path in sorted(plan.source.rglob("*.toml")):
                relative = toml_path.relative_to(plan.source)
                json_path = plan.target / relative.with_suffix(".json")
                try:
                    data = tomllib.loads(toml_path.read_text(encoding="utf-8"))
                except tomllib.TOMLDecodeError as exc:
                    errors.append(f"invalid TOML in {toml_path}: {exc}")
                    continue
                key = json_path.relative_to(resolved_root).as_posix()
                expected[key] = to_canonical_json(data)
        else:
            target_str = str(plan.target)
            if plan.target.is_dir() or target_str.endswith(("/", "\\")):
                json_path = plan.target / plan.source.with_suffix(".json").name
            elif plan.target.suffix == ".json":
                json_path = plan.target
            else:
                json_path = plan.target / plan.source.with_suffix(".json").name
            try:
                data = tomllib.loads(plan.source.read_text(encoding="utf-8"))
            except tomllib.TOMLDecodeError as exc:
                errors.append(f"invalid TOML in {plan.source}: {exc}")
                continue
            key = json_path.relative_to(resolved_root).as_posix()
            expected[key] = to_canonical_json(data)

    # WHY: data/export/index.json is generated by export as a manifest of the
    # other artifacts. Reproduce it here so it is not flagged as stale.
    index_path = resolved_root / "data" / "index.toml"
    if index_path.is_file():
        index = tomllib.loads(index_path.read_text(encoding="utf-8"))
        export_table = index.get("export")
        if isinstance(export_table, dict) and isinstance(
            export_table.get("index"), str
        ):
            manifest_path = (resolved_root / export_table["index"]).resolve()
            manifest_key = manifest_path.relative_to(resolved_root).as_posix()
            manifest = {
                "schema": "ar-export-index-1",
                "artifact_count": len(expected),
                "artifacts": sorted(expected),
            }
            expected[manifest_key] = to_canonical_json(manifest)

    return expected, errors


def validate_generated(root: Path) -> GeneratedValidation:
    """Compare committed generated JSON against a fresh regeneration.

    Args:
        root: Repository root.

    Returns:
        A :class:`GeneratedValidation`.
    """
    resolved_root = root.resolve()
    validation = GeneratedValidation()

    expected, errors = _expected_outputs(resolved_root)
    validation.failures.extend(errors)

    for relative, expected_text in sorted(expected.items()):
        path = resolved_root / relative
        if not path.is_file():
            validation.failures.append(f"missing generated file: {relative}")
            continue
        actual_text = path.read_text(encoding="utf-8")
        validation.compared += 1
        if actual_text != expected_text:
            validation.failures.append(
                f"generated file out of date: {relative} (run export)"
            )

    # Detect stale export files the source would no longer produce.
    export_root = resolved_root / "data" / "export"
    if export_root.is_dir():
        expected_paths = set(expected)
        for path in sorted(export_root.rglob("*.json")):
            relative = path.relative_to(resolved_root).as_posix()
            if relative not in expected_paths:
                validation.failures.append(f"stale generated file: {relative}")

    return validation
